# Generated by Django 5.1.1 on 2024-10-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.RenameField(
            model_name='frase',
            old_name='Alumno_fk',
            new_name='alumno_fk',
        ),
        migrations.RenameField(
            model_name='frase',
            old_name='cometario',
            new_name='comentario',
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='Alumnos',
        ),
    ]
